# Generated by Django 4.2 on 2023-04-23 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0003_auto_20190729_1611'),
    ]

    operations = [
        migrations.RenameField(
            model_name='match',
            old_name='total_runs',
            new_name='total_runs',
        ),
        migrations.RenameField(
            model_name='match',
            old_name='wicket',
            new_name='wicket',
        ),
    ]
