# Generated by Django 4.2 on 2023-04-23 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0007_club_points'),
    ]

    operations = [
        migrations.AlterField(
            model_name='club',
            name='ligue',
            field=models.CharField(choices=[('IPL', 'IPL'), ('WP', 'WP')], default='IPL', max_length=5),
        ),
    ]
