# Generated by Django 4.2 on 2023-04-23 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0004_player_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='clean_sheets',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
